### PR TITLE
Add documentation on Execution Model Inversion

### PR DESCRIPTION
**Pull request by guill**
This PR updates documentation for the changes from the Execution Model Inversion PR.

I also fixed some incorrect documentation I found.

### CODE REVIEW

**Comment by UrzasLegacy** [comment]
"spellcheck" is a valid input option for multiline widget :) and "placeholder" for text widgets

**Comment by guill** [comment]
I added three missing "Additional Parameters": `placeholder`, `label_on`, and `label_off`.

@UrzasLegacy It doesn't look like `spellcheck` does anything for me. Are you sure that's supported by the default UI and isn't added by some custom node pack?

**Comment by UrzasLegacy** [comment]
@guill spellcheck option is added in the new frontend
https://github.com/Comfy-Org/ComfyUI_frontend/blob/711205b499da86b41d04ad23bbc774743c6500f6/src/scripts/widgets.ts#L320

**Comment by guill** [comment]
Ah, that makes sense 👍 I would lean towards adding new functionality from the new front-end in a separate PR from the functionality from the updated execution model.

**Pull request merged**
